# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "."
          build-command: "make dirhtml"
      - name: Cache artifacts
        uses: actions/cache@v2
        if: github.ref == 'refs/heads/main'
        with:
          key: html-${{ github.sha }}
          path: ./_build/dirhtml
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Cache artifacts
        uses: actions/cache@v2
        with:
          key: html-${{ github.sha }}
          path: ./_build/dirhtml
      - run: touch ./_build/dirhtml/nojekyll
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: ./_build/dirhtml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
